{
	"_type": "Project",
	"_id": "AAAAAAFF+h6SjaM2Hec=",
	"name": "Untitled",
	"ownedElements": [
		{
			"_type": "UMLModel",
			"_id": "AAAAAAFF+qBWK6M3Z8Y=",
			"_parent": {
				"$ref": "AAAAAAFF+h6SjaM2Hec="
			},
			"name": "Model",
			"ownedElements": [
				{
					"_type": "UMLClassDiagram",
					"_id": "AAAAAAFF+qBtyKM79qY=",
					"_parent": {
						"$ref": "AAAAAAFF+qBWK6M3Z8Y="
					},
					"name": "Main",
					"defaultDiagram": true
				},
				{
					"_type": "ERDDataModel",
					"_id": "AAAAAAGAV0G02W5AmE8=",
					"_parent": {
						"$ref": "AAAAAAFF+qBWK6M3Z8Y="
					},
					"name": "Data Model1",
					"ownedElements": [
						{
							"_type": "ERDDiagram",
							"_id": "AAAAAAGAV0G02m5Bpv0=",
							"_parent": {
								"$ref": "AAAAAAGAV0G02W5AmE8="
							},
							"name": "ColchonesS.A.S",
							"ownedViews": [
								{
									"_type": "ERDEntityView",
									"_id": "AAAAAAGAV0HFSG5HJsM=",
									"_parent": {
										"$ref": "AAAAAAGAV0G02m5Bpv0="
									},
									"model": {
										"$ref": "AAAAAAGAV0HFSG5FD80="
									},
									"subViews": [
										{
											"_type": "LabelView",
											"_id": "AAAAAAGAV0HFSG5Ie8U=",
											"_parent": {
												"$ref": "AAAAAAGAV0HFSG5HJsM="
											},
											"font": "Arial;13;1",
											"left": 320,
											"top": 285,
											"width": 193,
											"height": 13,
											"text": "Empresa"
										},
										{
											"_type": "ERDColumnCompartmentView",
											"_id": "AAAAAAGAV0HFSG5JKNs=",
											"_parent": {
												"$ref": "AAAAAAGAV0HFSG5HJsM="
											},
											"model": {
												"$ref": "AAAAAAGAV0HFSG5FD80="
											},
											"subViews": [
												{
													"_type": "ERDColumnView",
													"_id": "AAAAAAGAV9ou9G5Xrv8=",
													"_parent": {
														"$ref": "AAAAAAGAV0HFSG5JKNs="
													},
													"model": {
														"$ref": "AAAAAAGAV9ou6G5Uaic="
													},
													"font": "Arial;13;0",
													"left": 325,
													"top": 308,
													"width": 183,
													"height": 13
												},
												{
													"_type": "ERDColumnView",
													"_id": "AAAAAAGAV9o4SW5dp/c=",
													"_parent": {
														"$ref": "AAAAAAGAV0HFSG5JKNs="
													},
													"model": {
														"$ref": "AAAAAAGAV9o4RG5aYek="
													},
													"font": "Arial;13;0",
													"left": 325,
													"top": 323,
													"width": 183,
													"height": 13
												},
												{
													"_type": "ERDColumnView",
													"_id": "AAAAAAGAV9pOg25mCOE=",
													"_parent": {
														"$ref": "AAAAAAGAV0HFSG5JKNs="
													},
													"model": {
														"$ref": "AAAAAAGAV9pOf25jVgU="
													},
													"visible": false,
													"font": "Arial;13;0",
													"left": 501,
													"top": 274,
													"width": 310,
													"height": 13
												}
											],
											"font": "Arial;13;0",
											"left": 320,
											"top": 303,
											"width": 193,
											"height": 38
										}
									],
									"font": "Arial;13;0",
									"left": 320,
									"top": 280,
									"width": 193,
									"height": 65,
									"nameLabel": {
										"$ref": "AAAAAAGAV0HFSG5Ie8U="
									},
									"columnCompartment": {
										"$ref": "AAAAAAGAV0HFSG5JKNs="
									}
								},
								{
									"_type": "ERDEntityView",
									"_id": "AAAAAAGAV9ttTm54B6I=",
									"_parent": {
										"$ref": "AAAAAAGAV0G02m5Bpv0="
									},
									"model": {
										"$ref": "AAAAAAGAV9ttTm52o+U="
									},
									"subViews": [
										{
											"_type": "LabelView",
											"_id": "AAAAAAGAV9ttTm55qwM=",
											"_parent": {
												"$ref": "AAAAAAGAV9ttTm54B6I="
											},
											"font": "Arial;13;1",
											"left": 64,
											"top": 405,
											"width": 214.7041015625,
											"height": 13,
											"text": "sede"
										},
										{
											"_type": "ERDColumnCompartmentView",
											"_id": "AAAAAAGAV9ttTm56+Kk=",
											"_parent": {
												"$ref": "AAAAAAGAV9ttTm54B6I="
											},
											"model": {
												"$ref": "AAAAAAGAV9ttTm52o+U="
											},
											"subViews": [
												{
													"_type": "ERDColumnView",
													"_id": "AAAAAAGAV9uGom6GnUY=",
													"_parent": {
														"$ref": "AAAAAAGAV9ttTm56+Kk="
													},
													"model": {
														"$ref": "AAAAAAGAV9uGnG6Deug="
													},
													"font": "Arial;13;0",
													"left": 69,
													"top": 428,
													"width": 204.7041015625,
													"height": 13
												},
												{
													"_type": "ERDColumnView",
													"_id": "AAAAAAGAV9uQmW6MtuQ=",
													"_parent": {
														"$ref": "AAAAAAGAV9ttTm56+Kk="
													},
													"model": {
														"$ref": "AAAAAAGAV9uQlG6JTfs="
													},
													"font": "Arial;13;0",
													"left": 69,
													"top": 443,
													"width": 204.7041015625,
													"height": 13
												},
												{
													"_type": "ERDColumnView",
													"_id": "AAAAAAGAV9uX4W6S3Yo=",
													"_parent": {
														"$ref": "AAAAAAGAV9ttTm56+Kk="
													},
													"model": {
														"$ref": "AAAAAAGAV9uX3W6Pkjw="
													},
													"font": "Arial;13;0",
													"left": 69,
													"top": 458,
													"width": 204.7041015625,
													"height": 13
												},
												{
													"_type": "ERDColumnView",
													"_id": "AAAAAAGAV9ueIm6Y8Kg=",
													"_parent": {
														"$ref": "AAAAAAGAV9ttTm56+Kk="
													},
													"model": {
														"$ref": "AAAAAAGAV9ueHW6VEJg="
													},
													"font": "Arial;13;0",
													"left": 69,
													"top": 473,
													"width": 204.7041015625,
													"height": 13
												},
												{
													"_type": "ERDColumnView",
													"_id": "AAAAAAGAV9vA+G6jRCA=",
													"_parent": {
														"$ref": "AAAAAAGAV9ttTm56+Kk="
													},
													"model": {
														"$ref": "AAAAAAGAV9vA9G6ggJ4="
													},
													"visible": false,
													"font": "Arial;13;0",
													"left": -83,
													"top": 440,
													"width": 204.7041015625,
													"height": 13
												}
											],
											"font": "Arial;13;0",
											"left": 64,
											"top": 423,
											"width": 214.7041015625,
											"height": 68
										}
									],
									"font": "Arial;13;0",
									"left": 64,
									"top": 400,
									"width": 214.7041015625,
									"height": 91,
									"nameLabel": {
										"$ref": "AAAAAAGAV9ttTm55qwM="
									},
									"columnCompartment": {
										"$ref": "AAAAAAGAV9ttTm56+Kk="
									}
								},
								{
									"_type": "ERDRelationshipView",
									"_id": "AAAAAAGAV90tBm67d7o=",
									"_parent": {
										"$ref": "AAAAAAGAV0G02m5Bpv0="
									},
									"model": {
										"$ref": "AAAAAAGAV90tBm63fgk="
									},
									"subViews": [
										{
											"_type": "EdgeLabelView",
											"_id": "AAAAAAGAV90tB268td4=",
											"_parent": {
												"$ref": "AAAAAAGAV90tBm67d7o="
											},
											"visible": false,
											"font": "Arial;13;0",
											"left": 191,
											"top": 297,
											"height": 13,
											"alpha": 1.5707963267948966,
											"distance": 15,
											"hostEdge": {
												"$ref": "AAAAAAGAV90tBm67d7o="
											},
											"edgePosition": 1
										},
										{
											"_type": "EdgeLabelView",
											"_id": "AAAAAAGAV90tB269Ho0=",
											"_parent": {
												"$ref": "AAAAAAGAV90tBm67d7o="
											},
											"font": "Arial;13;0",
											"left": 294,
											"top": 312,
											"height": 13,
											"alpha": 0.5235987755982988,
											"distance": 30,
											"hostEdge": {
												"$ref": "AAAAAAGAV90tBm67d7o="
											},
											"edgePosition": 2
										},
										{
											"_type": "EdgeLabelView",
											"_id": "AAAAAAGAV90tB26+4tA=",
											"_parent": {
												"$ref": "AAAAAAGAV90tBm67d7o="
											},
											"font": "Arial;13;0",
											"left": 191,
											"top": 368,
											"height": 13,
											"alpha": -0.5235987755982988,
											"distance": 30,
											"hostEdge": {
												"$ref": "AAAAAAGAV90tBm67d7o="
											}
										}
									],
									"font": "Arial;13;0",
									"head": {
										"$ref": "AAAAAAGAV9ttTm54B6I="
									},
									"tail": {
										"$ref": "AAAAAAGAV0HFSG5HJsM="
									},
									"lineStyle": 2,
									"points": "320:304;176:304;176:400",
									"nameLabel": {
										"$ref": "AAAAAAGAV90tB268td4="
									},
									"tailNameLabel": {
										"$ref": "AAAAAAGAV90tB269Ho0="
									},
									"headNameLabel": {
										"$ref": "AAAAAAGAV90tB26+4tA="
									}
								},
								{
									"_type": "ERDEntityView",
									"_id": "AAAAAAGAV91z7G7Qk0g=",
									"_parent": {
										"$ref": "AAAAAAGAV0G02m5Bpv0="
									},
									"model": {
										"$ref": "AAAAAAGAV91z7G7OR28="
									},
									"subViews": [
										{
											"_type": "LabelView",
											"_id": "AAAAAAGAV91z7G7Rils=",
											"_parent": {
												"$ref": "AAAAAAGAV91z7G7Qk0g="
											},
											"font": "Arial;13;1",
											"left": 352,
											"top": 405,
											"width": 216,
											"height": 13,
											"text": "productos"
										},
										{
											"_type": "ERDColumnCompartmentView",
											"_id": "AAAAAAGAV91z7W7StgE=",
											"_parent": {
												"$ref": "AAAAAAGAV91z7G7Qk0g="
											},
											"model": {
												"$ref": "AAAAAAGAV91z7G7OR28="
											},
											"subViews": [
												{
													"_type": "ERDColumnView",
													"_id": "AAAAAAGAV92PPG7eq5E=",
													"_parent": {
														"$ref": "AAAAAAGAV91z7W7StgE="
													},
													"model": {
														"$ref": "AAAAAAGAV92PM27b7ms="
													},
													"font": "Arial;13;0",
													"left": 357,
													"top": 428,
													"width": 206,
													"height": 13
												},
												{
													"_type": "ERDColumnView",
													"_id": "AAAAAAGAV92Vo27kNbI=",
													"_parent": {
														"$ref": "AAAAAAGAV91z7W7StgE="
													},
													"model": {
														"$ref": "AAAAAAGAV92VnW7hwAQ="
													},
													"font": "Arial;13;0",
													"left": 357,
													"top": 443,
													"width": 206,
													"height": 13
												},
												{
													"_type": "ERDColumnView",
													"_id": "AAAAAAGAV92ylm7vbvA=",
													"_parent": {
														"$ref": "AAAAAAGAV91z7W7StgE="
													},
													"model": {
														"$ref": "AAAAAAGAV92ykG7s/QY="
													},
													"font": "Arial;13;0",
													"left": 357,
													"top": 458,
													"width": 206,
													"height": 13
												},
												{
													"_type": "ERDColumnView",
													"_id": "AAAAAAGAV92502716Uo=",
													"_parent": {
														"$ref": "AAAAAAGAV91z7W7StgE="
													},
													"model": {
														"$ref": "AAAAAAGAV925z27yzO8="
													},
													"font": "Arial;13;0",
													"left": 357,
													"top": 473,
													"width": 206,
													"height": 13
												},
												{
													"_type": "ERDColumnView",
													"_id": "AAAAAAGAV93AHm77umE=",
													"_parent": {
														"$ref": "AAAAAAGAV91z7W7StgE="
													},
													"model": {
														"$ref": "AAAAAAGAV93AGG74DMI="
													},
													"font": "Arial;13;0",
													"left": 357,
													"top": 488,
													"width": 206,
													"height": 13
												},
												{
													"_type": "ERDColumnView",
													"_id": "AAAAAAGAV+cYYG8UPMs=",
													"_parent": {
														"$ref": "AAAAAAGAV91z7W7StgE="
													},
													"model": {
														"$ref": "AAAAAAGAV+cYVW8R8ak="
													},
													"font": "Arial;13;0",
													"left": 357,
													"top": 503,
													"width": 206,
													"height": 13
												}
											],
											"font": "Arial;13;0",
											"left": 352,
											"top": 423,
											"width": 216,
											"height": 98
										}
									],
									"font": "Arial;13;0",
									"left": 352,
									"top": 400,
									"width": 216,
									"height": 121,
									"nameLabel": {
										"$ref": "AAAAAAGAV91z7G7Rils="
									},
									"columnCompartment": {
										"$ref": "AAAAAAGAV91z7W7StgE="
									}
								},
								{
									"_type": "ERDRelationshipView",
									"_id": "AAAAAAGAV+fFZG8fuTM=",
									"_parent": {
										"$ref": "AAAAAAGAV0G02m5Bpv0="
									},
									"model": {
										"$ref": "AAAAAAGAV+fFY28b3XE="
									},
									"subViews": [
										{
											"_type": "EdgeLabelView",
											"_id": "AAAAAAGAV+fFZG8gZ10=",
											"_parent": {
												"$ref": "AAAAAAGAV+fFZG8fuTM="
											},
											"visible": false,
											"font": "Arial;13;0",
											"left": 315,
											"top": 445,
											"height": 13,
											"alpha": 1.5707963267948966,
											"distance": 15,
											"hostEdge": {
												"$ref": "AAAAAAGAV+fFZG8fuTM="
											},
											"edgePosition": 1
										},
										{
											"_type": "EdgeLabelView",
											"_id": "AAAAAAGAV+fFZG8h4ZY=",
											"_parent": {
												"$ref": "AAAAAAGAV+fFZG8fuTM="
											},
											"font": "Arial;13;0",
											"left": 303,
											"top": 445,
											"height": 13,
											"alpha": 0.5235987755982988,
											"distance": 30,
											"hostEdge": {
												"$ref": "AAAAAAGAV+fFZG8fuTM="
											},
											"edgePosition": 2
										},
										{
											"_type": "EdgeLabelView",
											"_id": "AAAAAAGAV+fFZG8iX2w=",
											"_parent": {
												"$ref": "AAAAAAGAV+fFZG8fuTM="
											},
											"font": "Arial;13;0",
											"left": 326,
											"top": 445,
											"height": 13,
											"alpha": -0.5235987755982988,
											"distance": 30,
											"hostEdge": {
												"$ref": "AAAAAAGAV+fFZG8fuTM="
											}
										}
									],
									"font": "Arial;13;0",
									"head": {
										"$ref": "AAAAAAGAV91z7G7Qk0g="
									},
									"tail": {
										"$ref": "AAAAAAGAV9ttTm54B6I="
									},
									"lineStyle": 2,
									"points": "278:466;352:466",
									"nameLabel": {
										"$ref": "AAAAAAGAV+fFZG8gZ10="
									},
									"tailNameLabel": {
										"$ref": "AAAAAAGAV+fFZG8h4ZY="
									},
									"headNameLabel": {
										"$ref": "AAAAAAGAV+fFZG8iX2w="
									}
								},
								{
									"_type": "ERDEntityView",
									"_id": "AAAAAAGAV+gA7W8ytEk=",
									"_parent": {
										"$ref": "AAAAAAGAV0G02m5Bpv0="
									},
									"model": {
										"$ref": "AAAAAAGAV+gA7W8wrao="
									},
									"subViews": [
										{
											"_type": "LabelView",
											"_id": "AAAAAAGAV+gA7W8zMwM=",
											"_parent": {
												"$ref": "AAAAAAGAV+gA7W8ytEk="
											},
											"font": "Arial;13;1",
											"left": 560,
											"top": 277,
											"width": 267.65625,
											"height": 13,
											"text": "ofertas"
										},
										{
											"_type": "ERDColumnCompartmentView",
											"_id": "AAAAAAGAV+gA7m80lME=",
											"_parent": {
												"$ref": "AAAAAAGAV+gA7W8ytEk="
											},
											"model": {
												"$ref": "AAAAAAGAV+gA7W8wrao="
											},
											"subViews": [
												{
													"_type": "ERDColumnView",
													"_id": "AAAAAAGAV+gdwW9A9UA=",
													"_parent": {
														"$ref": "AAAAAAGAV+gA7m80lME="
													},
													"model": {
														"$ref": "AAAAAAGAV+gduG89614="
													},
													"font": "Arial;13;0",
													"left": 565,
													"top": 300,
													"width": 257.65625,
													"height": 13
												},
												{
													"_type": "ERDColumnView",
													"_id": "AAAAAAGAV+glN29GhQ4=",
													"_parent": {
														"$ref": "AAAAAAGAV+gA7m80lME="
													},
													"model": {
														"$ref": "AAAAAAGAV+glMm9D/8M="
													},
													"font": "Arial;13;0",
													"left": 565,
													"top": 315,
													"width": 257.65625,
													"height": 13
												},
												{
													"_type": "ERDColumnView",
													"_id": "AAAAAAGAV+gslG9MrKo=",
													"_parent": {
														"$ref": "AAAAAAGAV+gA7m80lME="
													},
													"model": {
														"$ref": "AAAAAAGAV+gsj29JAHU="
													},
													"font": "Arial;13;0",
													"left": 565,
													"top": 330,
													"width": 257.65625,
													"height": 13
												},
												{
													"_type": "ERDColumnView",
													"_id": "AAAAAAGAV+g0/m9SoSM=",
													"_parent": {
														"$ref": "AAAAAAGAV+gA7m80lME="
													},
													"model": {
														"$ref": "AAAAAAGAV+g0+W9PflU="
													},
													"font": "Arial;13;0",
													"left": 565,
													"top": 345,
													"width": 257.65625,
													"height": 13
												}
											],
											"font": "Arial;13;0",
											"left": 560,
											"top": 295,
											"width": 267.65625,
											"height": 68
										}
									],
									"font": "Arial;13;0",
									"left": 560,
									"top": 272,
									"width": 267.65625,
									"height": 91,
									"nameLabel": {
										"$ref": "AAAAAAGAV+gA7W8zMwM="
									},
									"columnCompartment": {
										"$ref": "AAAAAAGAV+gA7m80lME="
									}
								},
								{
									"_type": "ERDRelationshipView",
									"_id": "AAAAAAGAV+sLHW+Dths=",
									"_parent": {
										"$ref": "AAAAAAGAV0G02m5Bpv0="
									},
									"model": {
										"$ref": "AAAAAAGAV+sLHW9/yTk="
									},
									"subViews": [
										{
											"_type": "EdgeLabelView",
											"_id": "AAAAAAGAV+sLHW+EWSw=",
											"_parent": {
												"$ref": "AAAAAAGAV+sLHW+Dths="
											},
											"visible": false,
											"font": "Arial;13;0",
											"left": 657,
											"top": 473,
											"height": 13,
											"alpha": 1.5707963267948966,
											"distance": 15,
											"hostEdge": {
												"$ref": "AAAAAAGAV+sLHW+Dths="
											},
											"edgePosition": 1
										},
										{
											"_type": "EdgeLabelView",
											"_id": "AAAAAAGAV+sLHW+Fi9M=",
											"_parent": {
												"$ref": "AAAAAAGAV+sLHW+Dths="
											},
											"font": "Arial;13;0",
											"left": 592,
											"top": 459,
											"height": 13,
											"alpha": 0.5235987755982988,
											"distance": 30,
											"hostEdge": {
												"$ref": "AAAAAAGAV+sLHW+Dths="
											},
											"edgePosition": 2
										},
										{
											"_type": "EdgeLabelView",
											"_id": "AAAAAAGAV+sLHW+G/o0=",
											"_parent": {
												"$ref": "AAAAAAGAV+sLHW+Dths="
											},
											"font": "Arial;13;0",
											"left": 657,
											"top": 381,
											"height": 13,
											"alpha": -0.5235987755982988,
											"distance": 30,
											"hostEdge": {
												"$ref": "AAAAAAGAV+sLHW+Dths="
											}
										}
									],
									"font": "Arial;13;0",
									"head": {
										"$ref": "AAAAAAGAV+gA7W8ytEk="
									},
									"tail": {
										"$ref": "AAAAAAGAV91z7G7Qk0g="
									},
									"lineStyle": 2,
									"points": "567:480;672:480;672:362",
									"nameLabel": {
										"$ref": "AAAAAAGAV+sLHW+EWSw="
									},
									"tailNameLabel": {
										"$ref": "AAAAAAGAV+sLHW+Fi9M="
									},
									"headNameLabel": {
										"$ref": "AAAAAAGAV+sLHW+G/o0="
									}
								}
							]
						},
						{
							"_type": "ERDEntity",
							"_id": "AAAAAAGAV0HFSG5FD80=",
							"_parent": {
								"$ref": "AAAAAAGAV0G02W5AmE8="
							},
							"name": "Empresa",
							"ownedElements": [
								{
									"_type": "ERDRelationship",
									"_id": "AAAAAAGAV90tBm63fgk=",
									"_parent": {
										"$ref": "AAAAAAGAV0HFSG5FD80="
									},
									"end1": {
										"_type": "ERDRelationshipEnd",
										"_id": "AAAAAAGAV90tBm64ago=",
										"_parent": {
											"$ref": "AAAAAAGAV90tBm63fgk="
										},
										"reference": {
											"$ref": "AAAAAAGAV0HFSG5FD80="
										}
									},
									"end2": {
										"_type": "ERDRelationshipEnd",
										"_id": "AAAAAAGAV90tBm65gS4=",
										"_parent": {
											"$ref": "AAAAAAGAV90tBm63fgk="
										},
										"reference": {
											"$ref": "AAAAAAGAV9ttTm52o+U="
										},
										"cardinality": "0..*"
									}
								}
							],
							"columns": [
								{
									"_type": "ERDColumn",
									"_id": "AAAAAAGAV9ou6G5Uaic=",
									"_parent": {
										"$ref": "AAAAAAGAV0HFSG5FD80="
									},
									"name": "id",
									"type": "INTEGER",
									"primaryKey": true
								},
								{
									"_type": "ERDColumn",
									"_id": "AAAAAAGAV9o4RG5aYek=",
									"_parent": {
										"$ref": "AAAAAAGAV0HFSG5FD80="
									},
									"name": "nombre",
									"type": "VARCHAR",
									"length": "100"
								},
								{
									"_type": "ERDColumn",
									"_id": "AAAAAAGAV9pOf25jVgU=",
									"_parent": {
										"$ref": "AAAAAAGAV0HFSG5FD80="
									},
									"name": "Column3"
								}
							]
						},
						{
							"_type": "ERDEntity",
							"_id": "AAAAAAGAV9ttTm52o+U=",
							"_parent": {
								"$ref": "AAAAAAGAV0G02W5AmE8="
							},
							"name": "sede",
							"ownedElements": [
								{
									"_type": "ERDRelationship",
									"_id": "AAAAAAGAV+fFY28b3XE=",
									"_parent": {
										"$ref": "AAAAAAGAV9ttTm52o+U="
									},
									"end1": {
										"_type": "ERDRelationshipEnd",
										"_id": "AAAAAAGAV+fFY28c8UQ=",
										"_parent": {
											"$ref": "AAAAAAGAV+fFY28b3XE="
										},
										"reference": {
											"$ref": "AAAAAAGAV9ttTm52o+U="
										}
									},
									"end2": {
										"_type": "ERDRelationshipEnd",
										"_id": "AAAAAAGAV+fFY28dYtY=",
										"_parent": {
											"$ref": "AAAAAAGAV+fFY28b3XE="
										},
										"reference": {
											"$ref": "AAAAAAGAV91z7G7OR28="
										},
										"cardinality": "0..*"
									}
								}
							],
							"columns": [
								{
									"_type": "ERDColumn",
									"_id": "AAAAAAGAV9uGnG6Deug=",
									"_parent": {
										"$ref": "AAAAAAGAV9ttTm52o+U="
									},
									"name": "id",
									"type": "INTEGER",
									"length": "10",
									"primaryKey": true
								},
								{
									"_type": "ERDColumn",
									"_id": "AAAAAAGAV9uQlG6JTfs=",
									"_parent": {
										"$ref": "AAAAAAGAV9ttTm52o+U="
									},
									"name": "direccion",
									"type": "VARCHAR",
									"length": "100"
								},
								{
									"_type": "ERDColumn",
									"_id": "AAAAAAGAV9uX3W6Pkjw=",
									"_parent": {
										"$ref": "AAAAAAGAV9ttTm52o+U="
									},
									"name": "ciudad",
									"type": "VARCHAR",
									"length": "100"
								},
								{
									"_type": "ERDColumn",
									"_id": "AAAAAAGAV9ueHW6VEJg=",
									"_parent": {
										"$ref": "AAAAAAGAV9ttTm52o+U="
									},
									"name": "id_empresa",
									"type": "INTEGER",
									"length": "10",
									"foreignKey": true
								},
								{
									"_type": "ERDColumn",
									"_id": "AAAAAAGAV9vA9G6ggJ4=",
									"_parent": {
										"$ref": "AAAAAAGAV9ttTm52o+U="
									},
									"name": "Column5"
								}
							]
						},
						{
							"_type": "ERDEntity",
							"_id": "AAAAAAGAV91z7G7OR28=",
							"_parent": {
								"$ref": "AAAAAAGAV0G02W5AmE8="
							},
							"name": "productos",
							"ownedElements": [
								{
									"_type": "ERDRelationship",
									"_id": "AAAAAAGAV+sLHW9/yTk=",
									"_parent": {
										"$ref": "AAAAAAGAV91z7G7OR28="
									},
									"end1": {
										"_type": "ERDRelationshipEnd",
										"_id": "AAAAAAGAV+sLHW+AQX0=",
										"_parent": {
											"$ref": "AAAAAAGAV+sLHW9/yTk="
										},
										"reference": {
											"$ref": "AAAAAAGAV91z7G7OR28="
										},
										"cardinality": "0..*"
									},
									"end2": {
										"_type": "ERDRelationshipEnd",
										"_id": "AAAAAAGAV+sLHW+BB9s=",
										"_parent": {
											"$ref": "AAAAAAGAV+sLHW9/yTk="
										},
										"reference": {
											"$ref": "AAAAAAGAV+gA7W8wrao="
										},
										"cardinality": "0..*"
									}
								}
							],
							"columns": [
								{
									"_type": "ERDColumn",
									"_id": "AAAAAAGAV92PM27b7ms=",
									"_parent": {
										"$ref": "AAAAAAGAV91z7G7OR28="
									},
									"name": "id",
									"type": "INTEGER",
									"length": "10",
									"primaryKey": true
								},
								{
									"_type": "ERDColumn",
									"_id": "AAAAAAGAV92VnW7hwAQ=",
									"_parent": {
										"$ref": "AAAAAAGAV91z7G7OR28="
									},
									"name": "nombre",
									"type": "VARCHAR",
									"length": "100"
								},
								{
									"_type": "ERDColumn",
									"_id": "AAAAAAGAV92ykG7s/QY=",
									"_parent": {
										"$ref": "AAAAAAGAV91z7G7OR28="
									},
									"name": "precio",
									"type": "INTEGER",
									"length": "50"
								},
								{
									"_type": "ERDColumn",
									"_id": "AAAAAAGAV925z27yzO8=",
									"_parent": {
										"$ref": "AAAAAAGAV91z7G7OR28="
									},
									"name": "descripcion",
									"type": "VARCHAR",
									"length": "200"
								},
								{
									"_type": "ERDColumn",
									"_id": "AAAAAAGAV93AGG74DMI=",
									"_parent": {
										"$ref": "AAAAAAGAV91z7G7OR28="
									},
									"name": "ofertas_id",
									"type": "INTEGER",
									"length": "10",
									"foreignKey": true
								},
								{
									"_type": "ERDColumn",
									"_id": "AAAAAAGAV+cYVW8R8ak=",
									"_parent": {
										"$ref": "AAAAAAGAV91z7G7OR28="
									},
									"name": "sede_id",
									"type": "INTEGER",
									"length": "10",
									"foreignKey": true
								}
							]
						},
						{
							"_type": "ERDEntity",
							"_id": "AAAAAAGAV+gA7W8wrao=",
							"_parent": {
								"$ref": "AAAAAAGAV0G02W5AmE8="
							},
							"name": "ofertas",
							"ownedElements": [
								{
									"_type": "ERDRelationship",
									"_id": "AAAAAAGAV+pkGW9h5Rg=",
									"_parent": {
										"$ref": "AAAAAAGAV+gA7W8wrao="
									},
									"end1": {
										"_type": "ERDRelationshipEnd",
										"_id": "AAAAAAGAV+pkGW9ihCs=",
										"_parent": {
											"$ref": "AAAAAAGAV+pkGW9h5Rg="
										},
										"reference": {
											"$ref": "AAAAAAGAV+gA7W8wrao="
										}
									},
									"end2": {
										"_type": "ERDRelationshipEnd",
										"_id": "AAAAAAGAV+pkGW9jxaY=",
										"_parent": {
											"$ref": "AAAAAAGAV+pkGW9h5Rg="
										},
										"reference": {
											"$ref": "AAAAAAGAV91z7G7OR28="
										},
										"cardinality": "0..*"
									}
								}
							],
							"columns": [
								{
									"_type": "ERDColumn",
									"_id": "AAAAAAGAV+gduG89614=",
									"_parent": {
										"$ref": "AAAAAAGAV+gA7W8wrao="
									},
									"name": "id",
									"type": "INTEGER",
									"length": "10",
									"primaryKey": true
								},
								{
									"_type": "ERDColumn",
									"_id": "AAAAAAGAV+glMm9D/8M=",
									"_parent": {
										"$ref": "AAAAAAGAV+gA7W8wrao="
									},
									"name": "fecha inicio",
									"type": "DATE"
								},
								{
									"_type": "ERDColumn",
									"_id": "AAAAAAGAV+gsj29JAHU=",
									"_parent": {
										"$ref": "AAAAAAGAV+gA7W8wrao="
									},
									"name": "fecha final",
									"type": "DATE"
								},
								{
									"_type": "ERDColumn",
									"_id": "AAAAAAGAV+g0+W9PflU=",
									"_parent": {
										"$ref": "AAAAAAGAV+gA7W8wrao="
									},
									"name": "porcentage descuento",
									"type": "INTEGER",
									"length": "20"
								}
							]
						}
					]
				}
			]
		}
	]
}